import PDFDocument from "pdfkit";

import type { PDFReportOptions } from "../../types/pdf.js";

class PDFExportService {
  async generatePDF<T extends object>(
    options: PDFReportOptions<T>,
  ): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({
        size: "A4",
        margin: 40,
      });

      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => chunks.push(chunk));

      doc.on("end", () => {
        resolve(Buffer.concat(chunks));
      });

      doc.on("error", reject);

      // -------------------------
      // Title
      // -------------------------
      doc.fontSize(20).font("Helvetica-Bold").text(options.title, {
        align: "center",
      });

      if (options.subtitle) {
        doc
          .moveDown(0.5)
          .fontSize(12)
          .font("Helvetica")
          .text(options.subtitle, {
            align: "center",
          });
      }

      doc.moveDown(2);

      // -------------------------
      // Metadata
      // -------------------------
      doc.fontSize(10).font("Helvetica");

      if (options.generatedBy) {
        doc.text(`Generated By : ${options.generatedBy}`);
      }

      const generatedOn = new Intl.DateTimeFormat("en-IN", {
        dateStyle: "medium",
        timeStyle: "short",
      }).format(new Date());

      doc.text(`Generated On : ${generatedOn}`);

      doc.moveDown(2);

      // -------------------------
      // Table Configuration
      // -------------------------
      const rowHeight = 22;

      const pageWidth =
        doc.page.width - doc.page.margins.left - doc.page.margins.right;

      const defaultWidth = pageWidth / options.columns.length;

      let currentY = doc.y;

      doc.font("Helvetica-Bold");
      doc.fontSize(10);

      const drawTableHeader = (y: number) => {
        doc.font("Helvetica-Bold");
        doc.fontSize(10);

        let currentX = doc.page.margins.left;

        options.columns.forEach((column) => {
          const width = column.width ?? defaultWidth;

          doc.rect(currentX, y, width, rowHeight).stroke();

          doc.text(column.title, currentX + 4, y + 6, {
            width: width - 8,
            align: column.align ?? "center",
          });

          currentX += width;
        });
      };

      drawTableHeader(currentY);

      currentY += rowHeight;

      doc.font("Helvetica");

      const drawFooter = () => {
        doc
          .fontSize(8)
          .fillColor("gray")
          .text(
            "Exam Management System",
            doc.page.margins.left,
            doc.page.height - 25,
            {
              align: "center",
            },
          );

        doc.fillColor("black");
      };

      options.rows.forEach((row) => {
        // Check if there's enough space for another row

        const heights = options.columns.map((column) => {
          const value = String(row[column.id] ?? "");

          return doc.heightOfString(value, {
            width: (column.width ?? defaultWidth) - 8,
          });
        });

        const calculatedRowHeight = Math.max(...heights) + 12;

        if (
          currentY + calculatedRowHeight >
          doc.page.height - doc.page.margins.bottom
        ) {
          drawFooter();
          doc.addPage();

          currentY = doc.page.margins.top;

          drawTableHeader(currentY);

          currentY += rowHeight;
        }

        let currentX = doc.page.margins.left;

        options.columns.forEach((column) => {
          const width = column.width ?? defaultWidth;

          doc.rect(currentX, currentY, width, calculatedRowHeight).stroke();

          const value = String(row[column.id] ?? "");

          doc.text(value, currentX + 4, currentY + 6, {
            width: width - 8,
            align: column.align ?? "left",
          });

          currentX += width;
        });

        currentY += calculatedRowHeight;
      });

      drawFooter();

      doc.end();
    });
  }
}

export default new PDFExportService();
